Add Documentation for setting up upstream IAMs with Keycloak
spiffe/tornjak pull request #419
Opened 2024-05-02 16:27 UTC by mamy-CS

2024-05-19 02:39 UTC, maia-iyer commented on docs/auth/keycloak/plugin_server_auth_keycloak.md
I would prefer this file stay in the original location `docs/plugin_server_auth_keycloak.md` because I'd like to keep all of the plugin config information in the same place. Instead, can this be linked somewhere in your newly provided documentation?

2024-05-20 18:48 UTC, maia-iyer requested changes
Left initial review. I followed the instructions for both Azure and Github and do not get the desired result. For Azure, it properly redirects me, but I cannot login with a user I need. 

For Github, it appears to attempt a redirect, but gives some error encoded in the URL about a redirect mismatch:

```
...error%3Dredirect_uri_mismatch%26error_description%3DThe%2Bredirect_uri%2BMUST%2Bmatch%2Bthe%2Bregistered%2Bcallback%2BURL%2Bfor%2Bthis%2Bapplication.%26error_uri%3Dhttps%253A%252F%252Fdocs.github.com%252Fapps%252Fmanaging-oauth-apps%252Ftroubleshooting-authorization-request-errors%252F%2523redirect-uri-mismatch...
```

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +> [!IMPORTANT] Make sure you assign appropraite roles within keycloak for your user, or the roles are mapped correctly between AD and keycloak. Check the Mappers section for more roles configuration.
Also is the Mappers section a TODO?

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +- Give your app a name in the `Application name` field such as `tornjak`, your application Homepage URL (http://localhost:3000) and the `Authorization callback URL` should be set to the `Redirect URI
same question as above for redirect URI

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +![Github OAuth](diagrams/github-oauth-app.png)
would also like to see this be a picture of filled in form

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +> [!NOTE] For simplicity we will be creating an OAUTH app under a personal github account. But you can create one under an organization you have admin access to. Github uses OAuth 2.0.
```suggestion
> [!NOTE] 
> For simplicity we will be creating an OAUTH app under a personal github account. But you can create one under an organization you have admin access to. Github uses OAuth 2.0.
```

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +> [!IMPORTANT] Make sure you are in the `tornjak` realm or te specific realm Tornjak app is registered on
```suggestion
> [!IMPORTANT]
> Make sure you are in the `tornjak` realm or te specific realm Tornjak app is registered on 
```

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +> [!IMPORTANT] Make sure you assign appropraite roles within keycloak for your user, or the roles are mapped correctly between github and keycloak.
```suggestion
> [!IMPORTANT] 
> Make sure you assign appropraite roles within keycloak for your user, or the roles are mapped correctly between github and keycloak. 
```

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +If you don't have an AD account, follow the instrctions below to create one.
```suggestion
If you don't have an AD account, follow the instructions below to create one. 
```

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +If you don't have a Github OAUTH app, follow the instrctions below to create one.
```suggestion
If you don't have a Github OAUTH app, follow the instructions below to create one. 
```

2024-05-20 18:48 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +- Click on the gear icon on the `Identity Provider Redirector` and set to the alias of the identity provider you want keycloak to redirect to.
Make this a separate section perhaps to separate this note from the Openshift for IAM section

2024-05-22 19:25 UTC, maia-iyer reviewed
I retested it, and I was able to get it to work - except Microsoft one requires you to select "Multitenant" so this detail needs to be added I think. I would add the details of a filled in form for each of keycloak and the upstream IDPs so that these details can be explained away

Also having gone through this I'm noticing the keycloak steps are pretty much always the same - maybe we can shorten the documentation. My suggestion would be to 
1. put the keycloak documentation at the top
  a. State where the relevant Redirect URI is (with the screen shot)
  b. Tell users to fill in the Client ID and Client Secret after obtaining them from the the desired IDP below
2. For each IDP create a collapsible section for readers to click into. 
  a. Talk about how to get to the relevant form to fill in Redirect URI
  b. Show a filled in picture of the form with the important selections
  
  
While Keycloak is technically the last step, I think this might be clear enough.

2024-05-23 17:29 UTC, mamy-CS commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +> [!IMPORTANT] Make sure you assign appropraite roles within keycloak for your user, or the roles are mapped correctly between AD and keycloak. Check the Mappers section for more roles configuration.
Yes. Will include the mappers section in consecutive pr. Need to do more research on that.

2024-05-30 19:24 UTC, maia-iyer reviewed
This is very clean! So I have a minor nit comment for the lines that go:
```
> [!TIP]
```

I think do a sweep through because some of them haven't put the rest of the text on the next line in order to parse properly 


I also do not see the TenantID field in Keycloak for Azure. Are you using the example in Tornjak repo or the helm charts? I'm using the example in Tornjak, so maybe it needs to be updated either with the right config. Probably can't remove the example in Tornjak repo to point to helm charts right now because that has the changes for the latest version of Tornjak to work with Keycloak. If you're using the helm charts, maybe make a note at the top about this should be sufficient?

2024-05-30 19:24 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +![Microsoft Keycloak](diagrams/microsoft-keycloak.png)
I do not have the microsoft keycloak Tenant ID here...

2024-05-30 19:24 UTC, maia-iyer commented on docs/auth/keycloak/keycloak-upstream-IAMs-conf.md
> +![Microsoft Keycloak](diagrams/microsoft-keycloak.png)
Which Keycloak are you running? Is it through our examples or through helm charts install?

2024-06-04 18:12 UTC, maia-iyer approved these changes
LGTM! Really great documentation!

2024-06-04 18:36 UTC, merged