Make dropdown open
spiffe/tornjak pull request #456
Opened 2024-06-18 20:47 UTC by Xiaocao-Cxh

Tell more about changes of codes.

2024-06-18 21:02 UTC, mamy-CS commented
Test Comment

2024-06-28 04:41 UTC, maia-iyer requested changes
Hello! nearly good, want to do the same for the other line in the file

2024-06-28 04:41 UTC, maia-iyer commented on docs/quickstart/README.md
>  <details><summary><b> 🔴 [Click] Run the Tornjak frontend locally</b></summary>
would you be able to make the same change in this line too?

2024-07-01 19:54 UTC, maia-iyer reviewed
LGTM! Thanks for doing this!

2024-07-01 19:54 UTC, maia-iyer approved these changes
Approving

2024-07-01 19:54 UTC, merged