Print Authorization Plugin Statements
spiffe/tornjak pull request #479
Opened 2024-08-13 21:39 UTC by Xiaocao-Cxh

Changes in the code:
- In docs/conf/agent/full.conf line 92, added new API with method: APIv1 "GET" "/api/v1/spire/serverinfo" { allowed_roles = ["admin", "viewer"] }
- In api/agent/types.go line 126-130 and 136 added structure APIv1RoleMapping.
- In api/agent/server.go line 1073 and 1076 added print statements to compare outputs of both old and the new API.

Outputs:
- For the old API, we got something normal like API name: /api/healthcheck, Allowed Roles: [admin viewer]
- For the new API, we got: API V1 method: GET, API V1 name: GET.

Evaluation:
As of our current progress, looks like our current structure for our new API does not get desired printed output. Maybe 2 keys with string type does not correctly mapped to list AllowedRoles. We may consider a different data structure for the new API.

2024-08-19 19:59 UTC, maia-iyer reviewed
Thanks for reporting on these results @Xiaocao-Cxh! I think based on this, we'll go with the path of least resistance - we'll stick with one "key" field as Name and in the parsing function, parse into two separate fields. So the above will parse the Name and AllowedRoles, but not Path or Method, which we can do in the print loop you added to `api/agent/server.go`

2024-08-19 19:59 UTC, maia-iyer commented on api/agent/types.go
> +}
```suggestion
type APIv1RoleMapping struct {
	Name string `hcl:",key"`
	Method string `hcl:"-"`
	Path string `hcl:"-"`
	AllowedRoles []string `hcl:"allowed_roles"`
}
```

2024-08-19 19:59 UTC, maia-iyer commented on api/agent/server.go
> +		for _, apiV1 := range config.APIv1RoleMappings{
need to add parsing to split string based on space

2024-08-21 04:03 UTC, Xiaocao-Cxh commented
I have updated the code we implemented today Tue, Aug 20 on types.go, server.go and full.conf.

2024-08-21 17:19 UTC, maia-iyer requested changes
Hello thanks for this! Some small nits; see below

2024-08-21 17:19 UTC, maia-iyer commented on api/agent/server.go
> +	apiRtr.HandleFunc("/api/v1/spire/bundles", s.bundleGet).Methods("GET")
revert this change; actually there is only one "spire bundle" so this is singular; all other resources can have multiple, so this should be plural

2024-08-21 17:19 UTC, maia-iyer commented on docs/conf/agent/full.conf
> +      APIv1 "GET /api/v1/spire/bundles" { allowed_roles = ["admin", "viewer"] }
so i suppose this should also be changed

2024-08-21 17:19 UTC, maia-iyer commented on docs/conf/agent/full.conf
> +      APIv1 "GET /api/v1/spire/serverinfo" { allowed_roles = ["admin", "viewer"] }
I think may be missing healthcheck api

2024-08-21 17:19 UTC, maia-iyer commented on docs/conf/agent/full.conf
> +  # }
Please uncomment these; double check the rest of the changes in full.conf because it seems git is not showing a smarter diff

2024-08-21 20:12 UTC, maia-iyer reviewed
Almost done just a couple nits!

2024-08-21 20:12 UTC, maia-iyer commented on docs/conf/agent/full.conf
> +  to the authorization layer as user roles.
sorry this should be commented out

2024-08-21 20:12 UTC, maia-iyer commented on docs/conf/agent/full.conf
> +      issuer = "http://localhost:8080/realms/tornjak"
```suggestion
      issuer = "http://host.docker.internal:8080/realms/tornjak"
```

2024-08-21 20:12 UTC, maia-iyer commented on docs/conf/agent/full.conf
> +      APIv1 "GET /api/v1/spire/entries" { allowed_roles = ["admin"] }
this is a duplicate; the one on line 94 is correct

2024-08-22 15:27 UTC, maia-iyer approved these changes
LGTM, thank you!

2024-08-22 15:27 UTC, merged